-- Deprecated hardcoded fallback army templates.
-- Runtime spawning should use runtime_roster_unit_data.lua + lib_runtime_army_template_generator.lua.
-- Keep this file only as a last-resort fallback if generated military_group data cannot resolve a faction.

return {
    -- Empire
    wh_main_sc_emp_empire = "wh_main_emp_swordsmen,wh_main_emp_swordsmen,wh_main_emp_swordsmen,wh_main_emp_swordsmen,wh_main_emp_handgunners,wh_main_emp_handgunners,wh_main_emp_crossbowmen,wh_main_emp_greatswords,wh_main_emp_greatswords,wh_main_emp_reiksguard,wh_main_emp_reiksguard,wh_main_emp_demigryph_knights,wh_main_art_great_cannon,wh_main_art_great_cannon,wh_main_art_helstorm_rocket_battery",

    -- Dwarfs
    wh_main_sc_dwf_dwarfs = "wh_main_dwf_dwarf_warriors,wh_main_dwf_dwarf_warriors,wh_main_dwf_longbeards,wh_main_dwf_longbeards,wh_main_dwf_hammerers,wh_main_dwf_hammerers,wh_main_dwf_ironbreakers,wh_main_dwf_ironbreakers,wh_main_dwf_quarrellers,wh_main_dwf_quarrellers,wh_main_dwf_thunderers,wh_main_dwf_thunderers,wh_main_dwf_cannon,wh_main_dwf_grudge_thrower,wh_main_dwf_organ_gun",

    -- High Elves
    wh2_main_sc_hef_high_elves = "wh2_main_hef_spearmen,wh2_main_hef_spearmen,wh2_main_hef_lothern_sea_guard,wh2_main_hef_lothern_sea_guard,wh2_main_hef_swordmasters_of_hoeth,wh2_main_hef_swordmasters_of_hoeth,wh2_main_hef_phoenix_guard,wh2_main_hef_phoenix_guard,wh2_main_hef_archers,wh2_main_hef_archers,wh2_main_hef_silver_helms,wh2_main_hef_dragon_princes,wh2_main_hef_eagle_claw_bolt_thrower,wh2_main_hef_eagle_claw_bolt_thrower,wh2_main_hef_phoenixes_flamespyre",

    -- Chaos
    wh_main_sc_chs_chaos = "wh_main_chs_chaos_warriors,wh_main_chs_chaos_warriors,wh_main_chs_chaos_warriors,wh_main_chs_chaos_warriors,wh_main_chs_chosen,wh_main_chs_chosen,wh_main_chs_chosen,wh_main_chs_forsaken,wh_main_chs_chaos_knights,wh_main_chs_chaos_knights,wh_main_chs_gorebeast_chariot,wh_main_chs_chaos_spawn,wh_main_chs_dragon_ogres,wh_main_chs_hellcannon,wh3_main_chs_chaos_warshrine",

    -- Khorne
    wh3_main_sc_kho_khorne = "wh3_main_kho_bloodletters,wh3_main_kho_bloodletters,wh3_main_kho_bloodletters,wh3_main_kho_bloodletters,wh3_main_kho_flesh_hounds_of_khorne,wh3_main_kho_flesh_hounds_of_khorne,wh3_main_kho_bloodcrushers,wh3_main_kho_bloodcrushers,wh3_main_kho_minotaurs_of_khorne,wh3_main_kho_minotaurs_of_khorne,wh3_main_kho_chaos_warriors_of_khorne,wh3_main_kho_chaos_warriors_of_khorne,wh3_main_kho_skullcannon,wh3_main_kho_skullcannon,wh3_main_kho_soul_grinder_of_khorne",

    -- Nurgle
    wh3_main_sc_nur_nurgle = "wh3_main_nur_plaguebearers,wh3_main_nur_plaguebearers,wh3_main_nur_plaguebearers,wh3_main_nur_nurglings,wh3_main_nur_nurglings,wh3_main_nur_plague_drones,wh3_main_nur_plague_drones,wh3_main_nur_beasts_of_nurgle,wh3_main_nur_beasts_of_nurgle,wh3_main_nur_rot_flies,wh3_main_nur_chaos_furies_of_nurgle,wh3_main_nur_chaos_spawn_of_nurgle,wh3_main_nur_soul_grinder_of_nurgle,wh3_main_nur_great_unclean_one,wh3_main_nur_great_unclean_one",

    -- Slaanesh
    wh3_main_sc_sla_slaanesh = "wh3_main_sla_daemonettes,wh3_main_sla_daemonettes,wh3_main_sla_daemonettes,wh3_main_sla_daemonettes,wh3_main_sla_seekers,wh3_main_sla_seekers,wh3_main_sla_hellstriders,wh3_main_sla_hellstriders,wh3_main_sla_fiends_of_slaanesh,wh3_main_sla_fiends_of_slaanesh,wh3_main_sla_seeker_chariots,wh3_main_sla_chaos_furies_of_slaanesh,wh3_main_sla_chaos_spawn_of_slaanesh,wh3_main_sla_soul_grinder_of_slaanesh,wh3_main_sla_keeper_of_secrets",

    -- Tzeentch
    wh3_main_sc_tze_tzeentch = "wh3_main_tze_pink_horrors,wh3_main_tze_pink_horrors,wh3_main_tze_pink_horrors,wh3_main_tze_blue_horrors,wh3_main_tze_blue_horrors,wh3_main_tze_flamers,wh3_main_tze_flamers,wh3_main_tze_screamers,wh3_main_tze_screamers,wh3_main_tze_chaos_furies_of_tzeentch,wh3_main_tze_exalted_flamers,wh3_main_tze_burning_chariot_of_tzeentch,wh3_main_tze_soul_grinder_of_tzeentch,wh3_main_tze_lord_of_change,wh3_main_tze_lord_of_change",

    -- Vampire Counts
    wh_main_sc_vmp_vampire_counts = "wh_main_vmp_skeleton_warriors,wh_main_vmp_skeleton_warriors,wh_main_vmp_grave_guard,wh_main_vmp_grave_guard,wh_main_vmp_grave_guard,wh_main_vmp_black_knights,wh_main_vmp_black_knights,wh_main_vmp_blood_knights,wh_main_vmp_crypt_horrors,wh_main_vmp_crypt_horrors,wh_main_vmp_vargheists,wh_main_vmp_vargheists,wh_main_vmp_terrorgheist,wh_main_vmp_varghulf,wh_main_vmp_zombie_dragon_death",

    -- Dark Elves
    wh2_main_sc_def_dark_elves = "wh2_main_def_darkshards_0,wh2_main_def_darkshards_0,wh2_main_def_bleakswords_0,wh2_main_def_bleakswords_0,wh2_main_def_black_guard_0,wh2_main_def_black_guard_0,wh2_main_def_executioners_0,wh2_main_def_executioners_0,wh2_main_def_shades_0,wh2_main_def_shades_0,wh2_main_def_cold_one_knights_0,wh2_main_def_cold_one_knights_0,wh2_main_def_war_hydra,wh2_main_def_reaper_bolt_thrower,wh2_main_def_black_dragon",

    -- Lizardmen
    wh2_main_sc_lzd_lizardmen = "wh2_main_lzd_saurus_warriors_0,wh2_main_lzd_saurus_warriors_0,wh2_main_lzd_saurus_warriors_1,wh2_main_lzd_saurus_warriors_1,wh2_main_lzd_temple_guards,wh2_main_lzd_temple_guards,wh2_main_lzd_cold_one_riders_0,wh2_main_lzd_cold_one_riders_0,wh2_main_lzd_chameleon_skinks_0,wh2_main_lzd_terradon_riders_0,wh2_main_lzd_stegadon_0,wh2_main_lzd_stegadon_0,wh2_main_lzd_carnosaur_0,wh2_main_lzd_bastiladon_0,wh2_main_lzd_ancient_stegadon",

    -- Skaven
    wh2_main_sc_skv_skaven = "wh2_main_skv_clanrats_0,wh2_main_skv_clanrats_0,wh2_main_skv_stormvermin_0,wh2_main_skv_stormvermin_0,wh2_main_skv_plague_monks,wh2_main_skv_plague_monks,wh2_main_skv_death_runners_0,wh2_main_skv_gutter_runners_0,wh2_main_skv_ratling_gun,wh2_main_skv_ratling_gun,wh2_main_skv_warpfire_thrower,wh2_main_skv_plagueclaw_catapult,wh2_main_skv_doomwheel,wh2_main_skv_hell_pit_abomination,wh2_dlc12_skv_doom_flayer",

    -- Tomb Kings
    wh2_dlc09_sc_tmb_tomb_kings = "wh2_dlc09_tmb_skeleton_warriors_0,wh2_dlc09_tmb_skeleton_warriors_0,wh2_dlc09_tmb_skeleton_spearmen_0,wh2_dlc09_tmb_skeleton_spearmen_0,wh2_dlc09_tmb_tomb_guard_0,wh2_dlc09_tmb_tomb_guard_0,wh2_dlc09_tmb_tomb_guard_1,wh2_dlc09_tmb_nehekhara_warriors_0,wh2_dlc09_tmb_skeleton_archers_0,wh2_dlc09_tmb_skeleton_horsemen_archers_0,wh2_dlc09_tmb_necropolis_knights_0,wh2_dlc09_tmb_ushabti_0,wh2_dlc09_tmb_warsphinx_0,wh2_dlc09_tmb_screaming_skull_catapult_0,wh2_dlc09_tmb_hierotitan_0",

    -- Vampire Coast
    wh2_dlc11_sc_cst_vampire_coast = "wh2_dlc11_cst_zombie_deckhands_mob_0,wh2_dlc11_cst_zombie_deckhands_mob_0,wh2_dlc11_cst_zombie_deckhands_mob_1,wh2_dlc11_cst_zombie_deckhands_mob_1,wh2_dlc11_cst_depth_guard_0,wh2_dlc11_cst_depth_guard_0,wh2_dlc11_cst_depth_guard_1,wh2_dlc11_cst_deck_gunners_0,wh2_dlc11_cst_deck_gunners_0,wh2_dlc11_cst_rotting_prometheans_0,wh2_dlc11_cst_mournguls_0,wh2_dlc11_cst_necrofex_colossus_0,wh2_dlc11_cst_queen_bess,wh2_dlc11_cst_terrorgheist,wh2_dlc11_cst_rotting_leviathan",

    -- Greenskins
    wh_main_sc_grn_greenskins = "wh_main_grn_orc_boyz,wh_main_grn_orc_boyz,wh_main_grn_orc_big_uns,wh_main_grn_orc_big_uns,wh_main_grn_black_orcs,wh_main_grn_black_orcs,wh_main_grn_goblin_archers,wh_main_grn_goblin_archers,wh_main_grn_night_goblin_fanatics,wh_main_grn_orc_boar_boyz_big_uns,wh_main_grn_orc_boar_boy_big_uns,wh_main_grn_arachnarok_spider_0,wh_main_grn_giant,wh_main_grn_doom_diver_catapult,wh_dlc06_grn_squig_hoppers_0",

    -- Bretonnia
    wh_main_sc_brt_bretonnia = "wh_main_brt_peasant_bowmen,wh_main_brt_peasant_bowmen,wh_main_brt_men_at_arms,wh_main_brt_men_at_arms,wh_main_brt_men_at_arms_polearm,wh_main_brt_foot_squires,wh_main_brt_knights_of_the_realm,wh_main_brt_knights_of_the_realm,wh_main_brt_questing_knights,wh_main_brt_questing_knights,wh_main_brt_grail_knights,wh_main_brt_grail_knights,wh_main_brt_pegasus_knights,wh_main_brt_royal_hippogryph_knights,wh_main_brt_field_trebuchet",

    -- Wood Elves
    wh_dlc05_sc_wef_wood_elves = "wh_dlc05_wef_eternal_guard_0,wh_dlc05_wef_eternal_guard_0,wh_dlc05_wef_wildwood_rangers_0,wh_dlc05_wef_wildwood_rangers_0,wh_dlc05_wef_wardancers_0,wh_dlc05_wef_wardancers_0,wh_dlc05_wef_glade_guard_0,wh_dlc05_wef_glade_guard_0,wh_dlc05_wef_waywatchers_0,wh_dlc05_wef_waywatchers_0,wh_dlc05_wef_wild_riders_0,wh_dlc05_wef_sisters_of_the_thorn_0,wh_dlc05_wef_forest_dragon_0,wh_dlc05_wef_treeman_0,wh_dlc05_wef_great_eagle_0",

    -- Beastmen
    wh_dlc03_sc_bst_beastmen = "wh_dlc03_bst_gor_herd_0,wh_dlc03_bst_gor_herd_0,wh_dlc03_bst_gor_herd_1,wh_dlc03_bst_bestigor_herd_0,wh_dlc03_bst_bestigor_herd_0,wh_dlc03_bst_minotaurs_0,wh_dlc03_bst_minotaurs_0,wh_dlc03_bst_minotaurs_2,wh_dlc03_bst_ungor_raiders_0,wh_dlc03_bst_ungor_raiders_0,wh_dlc03_bst_centigors_1,wh_dlc03_bst_centigors_1,wh_dlc03_bst_razorgor_chariot_0,wh_dlc03_bst_giant_0,wh_dlc03_bst_cygor_0",

    -- Norsca
    wh_dlc08_sc_nor_norsca = "wh_dlc08_nor_marauders_0,wh_dlc08_nor_marauders_0,wh_dlc08_nor_marauder_champions_0,wh_dlc08_nor_marauder_champions_0,wh_dlc08_nor_marauder_champions_1,wh_dlc08_nor_marauder_berserkers_0,wh_dlc08_nor_marauder_hunters_0,wh_dlc08_nor_marauder_hunters_0,wh_dlc08_nor_marauder_horsemen_0,wh_dlc08_nor_marauder_horsemasters_0,wh_dlc08_nor_skin_wolves_0,wh_dlc08_nor_fimir_0,wh_dlc08_nor_war_mammoth_0,wh_dlc08_nor_frost_wyrm_0,wh_dlc08_nor_war_mammoth_1",

    -- Kislev
    wh3_main_sc_ksl_kislev = "wh3_main_ksl_armoured_kossars_0,wh3_main_ksl_armoured_kossars_0,wh3_main_ksl_tzar_guard_0,wh3_main_ksl_tzar_guard_0,wh3_main_ksl_tzar_guard_1,wh3_main_ksl_streltsi_0,wh3_main_ksl_streltsi_0,wh3_main_ksl_ice_guard_0,wh3_main_ksl_ice_guard_0,wh3_main_ksl_winged_lancers_0,wh3_main_ksl_gryphon_legion_0,wh3_main_ksl_war_bear_riders_0,wh3_main_ksl_snow_leopard_0,wh3_main_ksl_little_grom_0,wh3_main_ksl_elemental_bear_0",

    -- Grand Cathay
    wh3_main_sc_cth_cathay = "wh3_main_cth_jade_warriors_0,wh3_main_cth_jade_warriors_0,wh3_main_cth_jade_warriors_1,wh3_main_cth_jade_warriors_1,wh3_main_cth_celestial_dragon_guard_0,wh3_main_cth_celestial_dragon_guard_0,wh3_main_cth_iron_hail_gunners_0,wh3_main_cth_iron_hail_gunners_0,wh3_main_cth_crane_gunners_0,wh3_main_cth_crane_gunners_0,wh3_main_cth_jade_lancers_0,wh3_main_cth_terracotta_sentinel_0,wh3_main_cth_terracotta_sentinel_0,wh3_main_cth_grand_cannon_0,wh3_main_cth_kongming_sky_lantern_0",

    -- Ogre Kingdoms
    wh3_main_sc_ogr_ogre_kingdoms = "wh3_main_ogr_ogres_0,wh3_main_ogr_ogres_0,wh3_main_ogr_ogres_1,wh3_main_ogr_ogres_1,wh3_main_ogr_ironguts_0,wh3_main_ogr_ironguts_0,wh3_main_ogr_leadbelchers_0,wh3_main_ogr_leadbelchers_0,wh3_main_ogr_mournfang_cavalry_0,wh3_main_ogr_mournfang_cavalry_0,wh3_main_ogr_maneaters_0,wh3_main_ogr_gorgers_0,wh3_main_ogr_stonehorn_0,wh3_main_ogr_ironblaster_0,wh3_main_ogr_giant_0",

    -- Chaos Dwarfs
    wh3_dlc23_sc_chd_chaos_dwarfs = "wh3_dlc23_chd_chaos_dwarf_warriors_0,wh3_dlc23_chd_chaos_dwarf_warriors_0,wh3_dlc23_chd_infernal_guard_0,wh3_dlc23_chd_infernal_guard_0,wh3_dlc23_chd_infernal_guard_1,wh3_dlc23_chd_infernal_ironsworn_0,wh3_dlc23_chd_blunderbuss_0,wh3_dlc23_chd_blunderbuss_0,wh3_dlc23_chd_bull_centaurs_0,wh3_dlc23_chd_bull_centaurs_1,wh3_dlc23_chd_kdaai_fireborn_0,wh3_dlc23_chd_iron_daemon_0,wh3_dlc23_chd_magma_cannon_0,wh3_dlc23_chd_great_taurus_0,wh3_dlc23_chd_kdaai_destroyer_0",

    -- Daemons of Chaos (undivided)
    wh3_main_sc_dae_daemons = "wh3_main_kho_bloodletters,wh3_main_kho_bloodletters,wh3_main_nur_plaguebearers,wh3_main_nur_plaguebearers,wh3_main_sla_daemonettes,wh3_main_sla_daemonettes,wh3_main_tze_pink_horrors,wh3_main_tze_pink_horrors,wh3_main_kho_flesh_hounds_of_khorne,wh3_main_nur_beasts_of_nurgle,wh3_main_sla_seekers,wh3_main_tze_screamers,wh3_main_kho_soul_grinder_of_khorne,wh3_main_nur_soul_grinder_of_nurgle,wh3_main_sla_soul_grinder_of_slaanesh",

    -- Default fallback
    default = "wh_main_chs_chaos_warriors,wh_main_chs_chaos_warriors,wh_main_chs_chaos_warriors,wh_main_chs_chaos_warriors,wh_main_chs_chosen,wh_main_chs_chosen,wh_main_chs_chaos_knights,wh_main_chs_chaos_knights,wh_main_chs_forsaken,wh_main_chs_forsaken,wh_main_chs_dragon_ogres,wh_main_chs_chaos_spawn,wh_main_chs_hellcannon,wh_main_chs_gorebeast_chariot,wh3_main_chs_chaos_warshrine",
}
